controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      Joint_1: { trajectory: 0.5, goal: 0.1 }
      Joint_2: { trajectory: 0.5, goal: 0.1 }
      Joint_3: { trajectory: 0.5, goal: 0.1 }
      Joint_4: { trajectory: 0.5, goal: 0.1 }
      Joint_5: { trajectory: 0.5, goal: 0.1 }
      Joint_6: { trajectory: 0.5, goal: 0.1 }

gripper_controller:
  ros__parameters:
    joints:
      - Gripper_Joint_1
      - Gripper_Joint_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true
